services:
  plant-disease-api:
    build: .
    network_mode: "host"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
